

export const personalityTypes = [
    {
        name: "logistician",
        code: "ISTJ",
        image: 'istj-logistician.svg',
        compatibility: [
            {
                code:'infp',
                score:20
            },
            {
                code:'enfp',
                score:20
            },
            {
                code:'infj',
                score:20
            },
            {
                code:'enfj',
                score:20
            },
            {
                code:'intj',
                score:40
            },
            {
                code:'entj',
                score:60
            },
            {
                code:'intp',
                score:40
            },
            {
                code:'entp',
                score:40
            },
            {
                code:'isfp',
                score:60
            },
            {
                code:'esfp',
                score:100
            },
            {
                code:'istp',
                score:60
            },
            {
                code:'estp',

                score:100
            },
            {
                code:'isfj',
                score:80
            },
            {
                code:'esfj',
                score:80
            },
            {
                code:'istj',
                score:80
            },
            {
                code:'estj',
                score:80
            },

        ]

    },
    {
        name: "defender",
        code: "ISFJ",
        image: 'isfj-defender.svg',
        compatibility: [
            {
                code:'infp',
                score:20
            },
            {
                code:'enfp',
                score:20
            },
            {
                code:'infj',
                score:20
            },
            {
                code:'enfj',
                score:20
            },
            {
                code:'intj',
                score:40
            },
            {
                code:'entj',
                score:60
            },
            {
                code:'intp',
                score:40
            },
            {
                code:'entp',
                score:40
            },
            {
                code:'isfp',
                score:60
            },
            {
                code:'esfp',
                score:100
            },
            {
                code:'istp',
                score:60
            },
            {
                code:'estp',

                score:100
            },
            {
                code:'isfj',
                score:80
            },
            {
                code:'esfj',
                score:80
            },
            {
                code:'istj',
                score:80
            },
            {
                code:'estj',
                score:80
            },

        ]
    },
    {
        name: "advocate",
        code: "INFJ",
        image: 'infj-advocate.svg',
        compatibility: [
            {
                code:'infp',
                score:80
            },
            {
                code:'enfp',
                score:100
            },
            {
                code:'infj',
                score:80
            },
            {
                code:'enfj',
                score:80
            },
            {
                code:'intj',
                score:80
            },
            {
                code:'entj',
                score:80
            },
            {
                code:'intp',
                score:80
            },
            {
                code:'entp',
                score:100
            },
            {
                code:'isfp',
                score:20
            },
            {
                code:'esfp',
                score:20
            },
            {
                code:'istp',
                score:20
            },
            {
                code:'estp',

                score:20
            },
            {
                code:'isfj',
                score:20
            },
            {
                code:'esfj',
                score:20
            },
            {
                code:'istj',
                score:20
            },
            {
                code:'estj',
                score:20
            },

        ]

    },
    {
        name: "architect",
        code: "INTJ",
        image: 'intj-architect.svg',
        compatibility: [
            {
                code:'infp',
                score:80
            },
            {
                code:'enfp',
                score:100
            },
            {
                code:'infj',
                score:80
            },
            {
                code:'enfj',
                score:80
            },
            {
                code:'intj',
                score:80
            },
            {
                code:'entj',
                score:80
            },
            {
                code:'intp',
                score:80
            },
            {
                code:'entp',
                score:100
            },
            {
                code:'isfp',
                score:60
            },
            {
                code:'esfp',
                score:60
            },
            {
                code:'istp',
                score:60
            },
            {
                code:'estp',

                score:60
            },
            {
                code:'isfj',
                score:40
            },
            {
                code:'esfj',
                score:40
            },
            {
                code:'istj',
                score:40
            },
            {
                code:'estj',
                score:40
            },

        ]
    },
    {
        name: "virtuoso",
        code: "ISTP",
        image: 'istp-virtuoso.svg',
        compatibility: [
            {
                code:'infp',
                score:20
            },
            {
                code:'enfp',
                score:20
            },
            {
                code:'infj',
                score:20
            },
            {
                code:'enfj',
                score:20
            },
            {
                code:'intj',
                score:60
            },
            {
                code:'entj',
                score:60
            },
            {
                code:'intp',
                score:60
            },
            {
                code:'entp',
                score:60
            },
            {
                code:'isfp',
                score:40
            },
            {
                code:'esfp',
                score:40
            },
            {
                code:'istp',
                score:40
            },
            {
                code:'estp',

                score:40
            },
            {
                code:'isfj',
                score:60
            },
            {
                code:'esfj',
                score:100
            },
            {
                code:'istj',
                score:60
            },
            {
                code:'estj',
                score:100
            },

        ]
    },
    {
        name: "adventurer",
        code: "ISFP",
        image: 'isfp-adventurer.svg',
        compatibility: [
            {
                code:'infp',
                score:20
            },
            {
                code:'enfp',
                score:20
            },
            {
                code:'infj',
                score:20
            },
            {
                code:'enfj',
                score:100
            },
            {
                code:'intj',
                score:60
            },
            {
                code:'entj',
                score:60
            },
            {
                code:'intp',
                score:60
            },
            {
                code:'entp',
                score:60
            },
            {
                code:'isfp',
                score:40
            },
            {
                code:'esfp',
                score:40
            },
            {
                code:'istp',
                score:40
            },
            {
                code:'estp',

                score:40
            },
            {
                code:'isfj',
                score:60
            },
            {
                code:'esfj',
                score:100
            },
            {
                code:'istj',
                score:60
            },
            {
                code:'estj',
                score:100
            },

        ]

    },
    {
        name: "mediator",
        code: "INFP",
        image: 'infp-mediator.svg',
        compatibility: [
            {
                code:'infp',
                score:80
            },
            {
                code:'infj',
                score:80
            },
            {
                code:'intj',
                score:80
            },
            {
                code:'istp',
                score:20
            },
            {
                code:'istj',
                score:20
            },
            {
                code:'isfp',
                score:20
            },
            {
                code:'isfj',
                score:20
            },
            {
                code:'entj',
                score:100
            },
            {
                code:'enfj',
                score:100
            },
            {
                code:'entp',
                score:80
            },
            {
                code:'enfp',
                score:80
            },
            {
                code:'estp',

                score:20
            },
            {
                code:'estj',
                score:20
            },
            {
                code:'esfp',
                score:20
            },
            {
                code:'esfj',
                score:20
            },
            {
                code:'intp',
                score:80
            },



        ]
    },
    {
        name: "logician",
        code: "INTP",
        image: 'intp-logician.svg',
        compatibility: [
            {
                code:'infp',
                score:80
            },
            {
                code:'enfp',
                score:80
            },
            {
                code:'infj',
                score:80
            },
            {
                code:'enfj',
                score:80
            },
            {
                code:'intj',
                score:80
            },
            {
                code:'entj',
                score:100
            },
            {
                code:'intp',
                score:80
            },
            {
                code:'entp',
                score:80
            },
            {
                code:'isfp',
                score:60
            },
            {
                code:'esfp',
                score:60
            },
            {
                code:'istp',
                score:60
            },
            {
                code:'estp',

                score:60
            },
            {
                code:'isfj',
                score:40
            },
            {
                code:'esfj',
                score:40
            },
            {
                code:'istj',
                score:40
            },
            {
                code:'estj',
                score:100
            },

        ]
    },
    {
        name: "entrepreneur",
        code: "ESTP",
        image: 'estp-entrepreneur.svg',
        compatibility: [
            {
                code:'infp',
                score:20
            },
            {
                code:'enfp',
                score:20
            },
            {
                code:'infj',
                score:20
            },
            {
                code:'enfj',
                score:20
            },
            {
                code:'intj',
                score:60
            },
            {
                code:'entj',
                score:60
            },
            {
                code:'intp',
                score:60
            },
            {
                code:'entp',
                score:60
            },
            {
                code:'isfp',
                score:40
            },
            {
                code:'esfp',
                score:40
            },
            {
                code:'istp',
                score:40
            },
            {
                code:'estp',

                score:40
            },
            {
                code:'isfj',
                score:100
            },
            {
                code:'esfj',
                score:60
            },
            {
                code:'istj',
                score:100
            },
            {
                code:'estj',
                score:60
            },

        ]
    },
    {
        name: "entertainer",
        code: "ESFP",
        image: 'esfp-entertainer.svg',
        compatibility: [
            {
                code:'infp',
                score:20
            },
            {
                code:'enfp',
                score:20
            },
            {
                code:'infj',
                score:20
            },
            {
                code:'enfj',
                score:20
            },
            {
                code:'intj',
                score:60
            },
            {
                code:'entj',
                score:60
            },
            {
                code:'intp',
                score:60
            },
            {
                code:'entp',
                score:60
            },
            {
                code:'isfp',
                score:40
            },
            {
                code:'esfp',
                score:40
            },
            {
                code:'istp',
                score:40
            },
            {
                code:'estp',

                score:40
            },
            {
                code:'isfj',
                score:100
            },
            {
                code:'esfj',
                score:60
            },
            {
                code:'istj',
                score:100
            },
            {
                code:'estj',
                score:60
            },

        ]
    },
    {
        name: "campaigner",
        code: "ENFP",
        image: 'enfp-campaigner.svg',
        compatibility: [
            {
                code:'infp',
                score:80
            },
            {
                code:'infj',
                score:100
            },
            {
                code:'intj',
                score:80
            },
            {
                code:'istp',
                score:20
            },
            {
                code:'istj',
                score:20
            },
            {
                code:'isfp',
                score:20
            },
            {
                code:'isfj',
                score:20
            },
            {
                code:'entj',
                score:100
            },
            {
                code:'enfj',
                score:80
            },
            {
                code:'entp',
                score:80
            },
            {
                code:'enfp',
                score:80
            },
            {
                code:'estp',

                score:20
            },
            {
                code:'estj',
                score:20
            },
            {
                code:'esfp',
                score:20
            },
            {
                code:'esfj',
                score:20
            },
            {
                code:'intp',
                score:80
            },



        ]
    },
    {
        name: "debater",
        code: "ENTP",
        image: 'entp-debater.svg',
        compatibility: [
            {
                code:'infp',
                score:80
            },
            {
                code:'enfp',
                score:80
            },
            {
                code:'infj',
                score:100
            },
            {
                code:'enfj',
                score:80
            },
            {
                code:'intj',
                score:100
            },
            {
                code:'entj',
                score:80
            },
            {
                code:'intp',
                score:80
            },
            {
                code:'entp',
                score:80
            },
            {
                code:'isfp',
                score:60
            },
            {
                code:'esfp',
                score:60
            },
            {
                code:'istp',
                score:60
            },
            {
                code:'estp',

                score:60
            },
            {
                code:'isfj',
                score:40
            },
            {
                code:'esfj',
                score:40
            },
            {
                code:'istj',
                score:40
            },
            {
                code:'estj',
                score:40
            },

        ]
    },
    {
        name: "executive",
        code: "ESTJ",
        image: 'estj-executive.svg',
        compatibility: [
            {
                code:'infp',
                score:20
            },
            {
                code:'enfp',
                score:20
            },
            {
                code:'infj',
                score:20
            },
            {
                code:'enfj',
                score:20
            },
            {
                code:'intj',
                score:40
            },
            {
                code:'entj',
                score:60
            },
            {
                code:'intp',
                score:100
            },
            {
                code:'entp',
                score:40
            },
            {
                code:'isfp',
                score:100
            },
            {
                code:'esfp',
                score:60
            },
            {
                code:'istp',
                score:100
            },
            {
                code:'estp',

                score:60
            },
            {
                code:'isfj',
                score:80
            },
            {
                code:'esfj',
                score:80
            },
            {
                code:'istj',
                score:80
            },
            {
                code:'estj',
                score:80
            },

        ]
    },
    {
        name: "consul",
        code: "ESFJ",
        image: 'esfj-consul.svg',
        compatibility: [
            {
                code:'infp',
                score:20
            },
            {
                code:'enfp',
                score:20
            },
            {
                code:'infj',
                score:20
            },
            {
                code:'enfj',
                score:20
            },
            {
                code:'intj',
                score:40
            },
            {
                code:'entj',
                score:60
            },
            {
                code:'intp',
                score:40
            },
            {
                code:'entp',
                score:40
            },
            {
                code:'isfp',
                score:100
            },
            {
                code:'esfp',
                score:60
            },
            {
                code:'istp',
                score:100
            },
            {
                code:'estp',

                score:60
            },
            {
                code:'isfj',
                score:80
            },
            {
                code:'esfj',
                score:80
            },
            {
                code:'istj',
                score:80
            },
            {
                code:'estj',
                score:80
            },

        ]
    },
    {
        name: "protagonist",
        code: "ENFJ",
        image: 'enfj-protagonist.svg',
        compatibility: [
            {
                code:'infp',
                score:100
            },
            {
                code:'enfp',
                score:80
            },
            {
                code:'infj',
                score:80
            },
            {
                code:'enfj',
                score:80
            },
            {
                code:'intj',
                score:80
            },
            {
                code:'entj',
                score:80
            },
            {
                code:'intp',
                score:80
            },
            {
                code:'entp',
                score:80
            },
            {
                code:'isfp',
                score:100
            },
            {
                code:'esfp',
                score:20
            },
            {
                code:'istp',
                score:20
            },
            {
                code:'estp',

                score:20
            },
            {
                code:'isfj',
                score:20
            },
            {
                code:'esfj',
                score:20
            },
            {
                code:'istj',
                score:20
            },
            {
                code:'estj',
                score:20
            },

        ]
    },
    {
        name: "commander",
        code: "ENTJ",
        image: 'entj-commander.svg',
        compatibility: [
            {
                code:'infp',
                score:100
            },
            {
                code:'enfp',
                score:80
            },
            {
                code:'infj',
                score:80
            },
            {
                code:'enfj',
                score:80
            },
            {
                code:'intj',
                score:80
            },
            {
                code:'entj',
                score:80
            },
            {
                code:'intp',
                score:100
            },
            {
                code:'entp',
                score:80
            },
            {
                code:'isfp',
                score:60
            },
            {
                code:'esfp',
                score:60
            },
            {
                code:'istp',
                score:60
            },
            {
                code:'estp',

                score:60
            },
            {
                code:'isfj',
                score:60
            },
            {
                code:'esfj',
                score:60
            },
            {
                code:'istj',
                score:60
            },
            {
                code:'estj',
                score:60
            },

        ]
    }
];
